### PR TITLE
add redis as extra package 

### PR DESCRIPTION
**Pull request by ME-ON1**
So Redis is not directly use in slowapi but is used by the dependency of it, limiter and is downgrading redis package ( this project has older version of it) which is already used in our project. 

So we can add redis as a extra package. 

This PR is for that @laurentS

### CODE REVIEW

**Comment by twcurrie** [comment]
This PR shifts redis into an optional package but doesn't handle the code dependencies within the codebase's test suite.  Please modify the test suite or modify the dependency installation so `redis` is included in the dev portion of the poetry file and therefore installed into the environment of the test execution.

**Comment by ME-ON1** [comment]
> This PR shifts redis into an optional package but doesn't handle the code dependencies within the test suite. Please modify the test suite or modify the dependency installation so `redis` is included in the dev portion of the poetry file and therefore installed into the environment of the test execution.

so currently redis in the code is only https://github.com/laurentS/slowapi/blob/b631980d701e7c34b092d16d74f35175b79328ce/tests/__init__.py#L6  used in the `tests/__init__.py` file in the import only and nowhere else, so it can be rm from slowapi 

and as limits has this as dependency and slowapi does have this redis as direct dependency. So rm does seems an option, what do you think about it ? !

**Comment by twcurrie** [comment]
Poetry lock is probably creating a merge conflict.  Merge with master and rerun `poetry lock`

**Review by twcurrie — APPROVED** [review]
I think this looks reasonable.

**Comment by twcurrie** [comment]
I looked at that, but the docs reference memcached, memory or redis.  We should likely add a line to give guidance on the ability to install redis with the library, but I wanted to revisit if memcached needed more clarity as well.

**Pull request merged**
