### PR TITLE
being able to ignore request parameter

### PR DESCRIPTION
**Pull request by aschenkuttel**
this allows users to use _ instead of request aswell which solves linter errors due the unused parameter
I'm aware that this strays a bit away from the same convention as starlette but looks to me a bit more pythonic

### CODE REVIEW

**Comment by laurentS** [comment]
Hi @aschenkuttel thanks for raising this PR!
In principle, I think it makes sense to try and resolve linter errors. I'm just wondering if there's a risk that some users might be using the `_` argument for other purposes, which could collide with your usage of it. Granted, they would need to use the correct type annotation as well, which seems unlikely.

**Comment by aschenkuttel** [comment]
I see what you mean but that should be already handled no? Since we still first check of the argument named request and only fallback onto the underscore if there's none?

So people are still able to use the request argument and ignore another one.

**Comment by twcurrie** [comment]
I'm uncertain about whether using `_` as a parameter is a positive change.  To resolve linter errors, I'd instead encourage the annotation `# noqa`.  From the library perspective, I'd rather default to the side of clarity.

**Comment by aschenkuttel** [comment]
I still think the underscore would be a positive change since we're using it as intended:

The request parameter is not used (by the user) hence the usage of the underscore instead.

Forcing the user to have this parameter with even a specific naming is just a weird concept in my eyes.

**Comment by twcurrie** [comment]
I agree, I think it's a bit clunky of a user experience.  I think the proposal to shift this into an [ASGI middleware implementation ](https://github.com/laurentS/slowapi/issues)would remove the need to declare the `request` object as a variable to every endpoint function.

**Comment by thentgesMindee** [comment]
Hi ! coming back to this PR that seems a bit forgotten:
- I agree with @twcurrie  and @laurentS here
>  From the library perspective, I'd rather default to the side of clarity. (twcurrie)

> I'm just wondering if there's a risk that some users might be using the _ argument for other purposes (laurentS)

I would say there is one, but as you said it would need to have the request annotation as well.
Maybe we could add a specific exception for the case where request is not defined, and _ is used for another purpose so that it is easier to debug.

Anyway, the #113 PR got merged, and Request doesn't have to be explicitely added, since it is created from the scope in the middleware:  `request = Request(scope, receive=receive, send=self.send)`, so we might close this PR

**Pull request closed without merging**
