### PR TITLE
fix: loosen restriction on the limits dependency

### LINKED ISSUE #156: slowapi uses limits==2.8.0 which contains usage of deprecated pkg_resources
**Describe the bug**

Our application uses `slowapi==0.1.7` which makes use of `limits==2.8.0`

The problem is `limits==2.8.0` uses `pkg_resources` which is deprecated and when we run tests they fail with:

```python
src/common/limiter.py:1: in <module>
    from slowapi.extension import Limiter
.nox/test-3-10-item/lib/python3.10/site-packages/slowapi/__init__.py:1: in <module>
    from .extension import Limiter, _rate_limit_exceeded_handler
.nox/test-3-10-item/lib/python3.10/site-packages/slowapi/extension.py:25: in <module>
    from limits import RateLimitItem  # type: ignore
.nox/test-3-10-item/lib/python3.10/site-packages/limits/__init__.py:5: in <module>
    from . import _version, aio, storage, strategies
.nox/test-3-10-item/lib/python3.10/site-packages/limits/aio/__init__.py:1: in <module>
    from . import storage, strategies
.nox/test-3-10-item/lib/python3.10/site-packages/limits/aio/storage/__init__.py:6: in <module>
    from .base import MovingWindowSupport, Storage
.nox/test-3-10-item/lib/python3.10/site-packages/limits/aio/storage/base.py:5: in <module>
    from limits.storage.registry import StorageRegistry
.nox/test-3-10-item/lib/python3.10/site-packages/limits/storage/__init__.py:12: in <module>
    from .base import MovingWindowSupport, Storage
.nox/test-3-10-item/lib/python3.10/site-packages/limits/storage/base.py:6: in <module>
    from limits.util import LazyDependency
.nox/test-3-10-item/lib/python3.10/site-packages/limits/util.py:11: in <module>
    import pkg_resources
.nox/test-3-10-item/lib/python3.10/site-packages/pkg_resources/__init__.py:121: in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
```

I tried to manually edit `.nox/test-3-10-item/lib/python3.10/site-packages/limits/util.py` and apply the fix (Remove deprecated use of pkg_resources and switch to importlib_resource) and we don't get the warning anymore.

**To Reproduce**

On Python 3.10 we get this warning when running tests through nox

**Expected behavior**

`limits` fixed the issue in 3.3.0 https://github.com/alisaifee/limits/blob/master/HISTORY.rst#v330

`slowapi` should use a more updated version of `limits`

**Screenshots**

(none)

**Your app (please complete the following information):**

Deps used:

```python
fastapi==0.95.0
limits==2.8.0
slowapi==0.1.7
```

**Python**: Python 3.10.9

**Additional context**

The best would be if `slowapi` could move to `limits>=3.3.0` so this problem would be solved.

In alternative, a way to suppress `E   DeprecationWarning: pkg_resources is deprecated as an API` could work as well.
Please note that this error is not happening on all our devs machines so I suspect other people may have some particular setting which is suppressing these warnings. The problem is that we can't find what it is.

Thanks

### PR DESCRIPTION
**Pull request by sanders41**
Closes #156

This is one possible solution to #156 if you want to keep supporting `limits` <3.0. The current setting caps `limits` at 2.x, this change will allow anything >= 2.3.  All the tests are passing so my assumption is none of the breaking changes in 3.0 cause issues here.

### CODE REVIEW

**Comment by andreagrandi** [comment]
Thanks @sanders41 ! I hope it gets merged and released 🙏🏻

**Comment by laurentS** [comment]
Hi @sanders41 thanks for opening this. It looks ok to me, particularly seeing that the CI checks used `limits == 3.3.1`.
@andreagrandi I'm merging now, please do report back if the new `master` branch is failing in any way for you.

**Review by laurentS — APPROVED** [review]

**Comment by andreagrandi** [comment]
> Hi @sanders41 thanks for opening this. It looks ok to me, particularly seeing that the CI checks used `limits == 3.3.1`. @andreagrandi I'm merging now, please do report back if the new `master` branch is failing in any way for you.

hi @laurentS first of all thank you so much for addressing this so quickly ❤️

I temporary changed my `requirements.txt` like this:
```python
# slowapi==0.1.7
git+https://github.com/laurentS/slowapi@master
```
and rerun our tests and I confirm I'm not getting that error anymore 🎉

It's worth noticing two things:

1) the error I was getting:
```python
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
```
was enough, in my case to make `nox` fail the test, but if I ran the tests with `pytest` directly, the warning wasn't "enough" to make the test fail.

2) A colleague of mine, tried in all possible ways (we replicated the same packages, same environment, same Python version etc....) to replicate the issue, but she wasn't able to replicate: on her machine she was indeed getting `warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)` but this warning wasn't enough to make `nox` fail. It's just like our systems had two different levels of failure 🤷🏻‍♂️

p.s: I'm looking forward to switch to the new version once released, in the mean time I will keep using the `master` branch version locally.

Thanks again 🙏🏻

**Comment by sanders41** [comment]
@andreagrandi I am guessing this isn't the reason, but any chance you have the environment variable `PYTHONWARNINGS` set to `error`? https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS

**Comment by andreagrandi** [comment]
> @andreagrandi I am guessing this isn't the reason, but any chance you have the environment variable `PYTHONWARNINGS` set to `error`? https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS

if I do `env | grep PYTHONWARNINGS` it gives me nothing

**Comment by sanders41** [comment]
Your result is the same as mine. I figured it was a long shot.

**Comment by laurentS** [comment]
Shameless call for help, I've opened https://github.com/laurentS/slowapi/pull/109 a few days ago to try and fix the blocking point around releases. If anyone has time to take a look, it'll be helpful.

@andreagrandi I don't know where your error comes from, I've never used `nox` directly. My only guess would be to check if `nox` isn't somehow using a "user level" config file, something like `~/.nox/config` or maybe you have a shell alias that replaces `nox` with `nox --some-stricter-option`?
Side note, feel free to open a release PR along the lines of https://github.com/laurentS/slowapi/pull/120 for `v0.1.8`, that should get you contributor access to the repo as per https://github.com/laurentS/slowapi/issues/58 :)

**Comment by andreagrandi** [comment]
> Side note, feel free to open a release PR along the lines of #120 for `v0.1.8`, that should get you contributor access to the repo as per #58 :)

I can definitely give it a try. My only blocker is that I never used `poetry` so I'm not sure how to regenerate that lock file, but I can try

**Comment by laurentS** [comment]
No pressure :)

> I can definitely give it a try. My only blocker is that I never used poetry so I'm not sure how to regenerate that lock file, but I can try

`poetry lock` will generate the lockfile, `poetry install` will do the same AND install the required dependencies. https://python-poetry.org/docs/cli/#lock for more details.

**Comment by andreagrandi** [comment]
I prepared this https://github.com/laurentS/slowapi/pull/159 but I still need to take care of `poetry.lock`

**Comment by andreagrandi** [comment]
```bash
➜  slowapi git:(prepare-release-0-1-8) poetry lock
Updating dependencies
Resolving dependencies... (4.0s)
➜  slowapi git:(prepare-release-0-1-8) git status
On branch prepare-release-0-1-8
Your branch is up to date with 'origin/prepare-release-0-1-8'.

nothing to commit, working tree clean
```
uhm

**Comment by sanders41** [comment]
I ran the lock to make sure `limits` was updated for testing so I'm guessing this is why you aren't getting any new updates.

**Comment by andreagrandi** [comment]
Perfect then! Please double check the changelog file, because I generated it by reading meaningful (imho) commit messages that were done after the last release. Thanks

**Pull request merged**
