### PR TITLE
chore: prepare release 0.1.8

### PR DESCRIPTION
**Pull request by andreagrandi**
This PR prepares the release `0.1.8`

### CODE REVIEW

**Review by laurentS — APPROVED** [review]
LGTM! Thanks for making this happen, I'm sure quite a few people are waiting for this :)

**Comment by laurentS** [comment]
And it's published! Thanks for the help @andreagrandi (I now realise we should have added you in the changelog thank yous :smile: )

**Comment by laurentS** [comment]
Invite sent, as promised!

**Comment by andreagrandi** [comment]
> And it's published! Thanks for the help @andreagrandi (I now realise we should have added you in the changelog thank yous 😄 )

no worries, feel free to add it for the next release if you want 😅
I'm going to test the new package, thanks!

**Pull request merged**
