### PR TITLE
Update dev dependencies to support python 3.11

### LINKED ISSUE #119: Add support for python 3.11
Now that it's officially released, we should add support for it, as it's full of good stuff :kiwi_fruit: :strawberry: :green_apple:

### PR DESCRIPTION
**Pull request by sanders41**
Closes #119

### CODE REVIEW

**Comment by sanders41** [comment]
Interesting mypy is failing here. I specifically ran pytest will multiple versions, but no mypy. I'll take a looking into why mypy would fail here.

**Comment by sanders41** [comment]
:facepalm: I forgot to remove those imports after making the updates. I looked through CI to check for any other tests that will run, and looks like black is the only other one. I ran that locally with no errors so we should be good now.

**Review by laurentS — APPROVED** [review]
Looks good to me!

**Comment by smittysmee** [comment]
@laurentS @sanders41 - Can we get this merged in and going?

**Comment by sanders41** [comment]
I believe it is ready to merge, but @laurentS if there is something else you want me to do just let me know.

**Comment by laurentS** [comment]
Done! Sorry, I assumed you were going to merge yourself after my previous comment, but I guess you're not actually allowed to do that!

**Comment by laurentS** [comment]
@sanders41 thank you for your contribution! As per #58 I've sent you an invite to join the repo.

**Comment by sanders41** [comment]
Thanks @laurentS, invite accepted

**Comment by smittysmee** [comment]
Legit. Thanks all.

**Comment by smittysmee** [comment]
@laurentS - What is your build process for getting this published? Looking to get this leveraged for 3.11 as I am starting an new project here shortly.

**Comment by smittysmee** [comment]
@laurentS - I am not seeing this published.

**Comment by laurentS** [comment]
Hi @smittysmee this is not my day job, it's 100% volunteer work, so priority may fall behind. The process for publishing an update is a bit manual still. If you want to give a hand with opening a PR to prepare for a release 0.1.8, I think a lot of people will be grateful. Examples from past releases #120 or #108. As a policy (see #58 ), I add any contributor who's had at least one PR merged to the repo, to help reduce bottlenecks. You're welcome to join the team!
Also, there's been some discussion around automating releases to prevent situations like this. If this is something you're interested in, feel free to look into it.

**Comment by smittysmee** [comment]
Add me to the team, I would love to help where I may. If I get time tonight, I will do this as well. (Same boat as you)

**Pull request merged**
