### PR TITLE
Prepare release 0.1.7

### PR DESCRIPTION
**Pull request by laurentS**
This is a just a small non-functional PR with some admin to prepare release 0.1.7.

Still hoping to get this automated sooner rather than later :)

### CODE REVIEW

**Comment by thentgesMindee** [comment]
Hi ! sorry for the review time!
I would love to get this release done in the coming days, but for some reason the CI fails

**Comment by thentgesMindee** [comment]
@laurentS, I'll probably have a bit of time next week, let me know if I can do anything to help in the release process

**Comment by laurentS** [comment]
@thentgesMindee CI is all green now. I got a little over-ambitious with python 3.11, we'll keep this for next release.
Feel free to review/approve if it looks ok to you, and I'll push the new release to `pypi`.

**Review by thentgesMindee — APPROVED** [review]
Looks good to me ! Thanks

**Comment by laurentS** [comment]
Release just published to [PyPI](https://pypi.org/project/slowapi/) :tada:

**Comment by thentgesMindee** [comment]
Cool perfect ! thanks a lot
Shouldn't we create a git tag to match the version on PyPI ?

**Comment by laurentS** [comment]
Good point about the tag, I just created it. Thanks!

**Pull request merged**
